/**
 * World 5 Chapters 7-9: Sequence Shores, Ratio Reef, Decimal Depths
 * 40 levels, 120 problems
 */
function mc(v, d) { return { value: v, displayValue: d || v }; }
function num(v, d) { return { value: Number(v), displayValue: d || String(v) }; }
function txt(v, d) { return { value: v, displayValue: d || v }; }
function hint(t, text, type) { return { tier: t, cost: [0,0,1,2][t], text, type }; }
function prob(id, lid, seq, o) {
  return { id, levelId: lid, sequence: seq, type: o.type||'numeric_input', category: o.cat||'thinking',
    statement: o.s, inputType: o.inp||'number_pad', correctAnswer: o.a, hints: o.h,
    solutionExplanation: o.sol, teachingPoint: o.tp, tags: o.tags||[], difficulty: o.d||2 };
}
function lev(id, cid, n, name, type, diff, story, problems) {
  return { id, chapterId: cid, worldId: 'world-5', number: n, name, type, storyContext: story,
    problems, difficulty: diff,
    estimatedMinutes: type==='boss'?10:type==='challenge'?7:type==='practice'?5:4,
    isChallenge: type==='challenge'||type==='boss', isBoss: type==='boss' };
}

// ━━━ CHAPTER 7 — Sequence Shores ━━━━━━━━━━━━━━━━━━━━━━━
function createChapter7() {
  const ch=7, cid=`chapter-5-${ch}`;
  const levels = [
    // 1 Constant Difference (teaching, 1)
    lev(`level-5-${ch}-1`,cid,1,'Constant Difference','teaching',1,
      'Lizzie discovers stepping stones. "Each stone is 3 more than the last! That\'s an arithmetic sequence."',
      [
        prob(`problem-5-${ch}-1-1`,`level-5-${ch}-1`,1,{s:'In the sequence 5, 8, 11, 14, ..., what is the common difference?',a:num(3,'Each term increases by 3'),h:[hint(1,'Compare consecutive terms: 8-5, 11-8, 14-11.','conceptual'),hint(2,'8-5=3, 11-8=3, 14-11=3. The difference is constant.','directional'),hint(3,'The common difference is 3.','scaffolded')],sol:'Common difference = 3',tp:'An arithmetic sequence has a constant difference between consecutive terms. Here each term is 3 more than the previous.',tags:['sequences','arithmetic','common-difference'],d:1}),
        prob(`problem-5-${ch}-1-2`,`level-5-${ch}-1`,2,{s:'What is the next term in 5, 8, 11, 14, ...?',a:num(17,'14+3=17'),h:[hint(1,'Add the common difference to the last term.','conceptual'),hint(2,'Common difference is 3. Last term is 14.','directional'),hint(3,'14+3=17.','scaffolded')],sol:'Next = 14+3=17',tp:'To find the next term in an arithmetic sequence, add the common difference to the last known term.',tags:['sequences','arithmetic','next-term'],d:1}),
        prob(`problem-5-${ch}-1-3`,`level-5-${ch}-1`,3,{s:'In the sequence 20, 15, 10, 5, ..., what is the common difference?',a:num(-5,'Each term decreases by 5'),h:[hint(1,'Subtract consecutive terms: 15-20, 10-15.','conceptual'),hint(2,'15-20=-5, 10-15=-5. The difference is negative.','directional'),hint(3,'Common difference = -5 (decreasing sequence).','scaffolded')],sol:'d = -5',tp:'Arithmetic sequences can decrease! A negative common difference means each term is smaller than the previous one.',tags:['sequences','arithmetic','decreasing'],d:1}),
      ]),
    // 2 Arithmetic Practice (practice, 2)
    lev(`level-5-${ch}-2`,cid,2,'Arithmetic Practice','practice',2,
      'Grogg fills in missing stepping stones. "I just keep adding the same number!"',
      [
        prob(`problem-5-${ch}-2-1`,`level-5-${ch}-2`,1,{cat:'pattern_discovery',s:'Find the missing term: 3, 7, ?, 15, 19.',a:num(11,'d=4, missing=7+4=11'),h:[hint(1,'Find the common difference from the known terms.','conceptual'),hint(2,'7-3=4 and 19-15=4, so d=4.','directional'),hint(3,'7+4=11.','scaffolded')],sol:'Missing = 11',tp:'When terms are missing, use the common difference to fill gaps. d=4: 3, 7, 11, 15, 19.',tags:['sequences','arithmetic','missing-term','pattern-discovery'],d:2}),
        prob(`problem-5-${ch}-2-2`,`level-5-${ch}-2`,2,{s:'Is 2, 5, 10, 17, 26 an arithmetic sequence? If not, what are the differences?',a:txt('No','Differences: 3,5,7,9 — not constant'),type:'text_input',inp:'text_field',h:[hint(1,'Calculate the differences between consecutive terms.','conceptual'),hint(2,'5-2=3, 10-5=5, 17-10=7, 26-17=9.','directional'),hint(3,'Differences are 3,5,7,9 — increasing, not constant. Not arithmetic.','scaffolded')],sol:'Not arithmetic — differences are 3,5,7,9',tp:'If the differences between terms are not constant, the sequence is NOT arithmetic. Check carefully!',tags:['sequences','arithmetic','identification'],d:2}),
        prob(`problem-5-${ch}-2-3`,`level-5-${ch}-2`,3,{s:'An arithmetic sequence starts at 4 with d=6. What is the 5th term?',a:num(28,'4, 10, 16, 22, 28'),h:[hint(1,'List terms: start at 4, add 6 each time.','conceptual'),hint(2,'4, 10, 16, 22, ?','directional'),hint(3,'22+6=28.','scaffolded')],sol:'5th term = 28',tp:'To find the nth term: start + (n-1)×d. Here: 4 + 4×6 = 28.',tags:['sequences','arithmetic','nth-term'],d:2}),
      ]),
    // 3 The nth Term (teaching, 2)
    lev(`level-5-${ch}-3`,cid,3,'The nth Term','teaching',2,
      'Prof. Owlbert writes a formula. "Instead of listing every term, we can use a rule: start + (n-1) × difference."',
      [
        prob(`problem-5-${ch}-3-1`,`level-5-${ch}-3`,1,{s:'Sequence: 3, 7, 11, 15, ... (start=3, d=4). What is the 10th term?',a:num(39,'3+(10-1)×4 = 3+36 = 39'),h:[hint(1,'Use the formula: term = start + (n-1) × d.','conceptual'),hint(2,'term₁₀ = 3 + (10-1) × 4 = 3 + 9×4.','directional'),hint(3,'3 + 36 = 39.','scaffolded')],sol:'10th term = 3 + 9×4 = 39',tp:'The nth term formula: aₙ = a₁ + (n-1)d. For start=3, d=4: a₁₀ = 3 + 9(4) = 39.',tags:['sequences','arithmetic','formula','nth-term'],d:2}),
        prob(`problem-5-${ch}-3-2`,`level-5-${ch}-3`,2,{s:'Sequence: 50, 45, 40, 35, ... (start=50, d=-5). What is the 8th term?',a:num(15,'50+(8-1)×(-5) = 50-35 = 15'),h:[hint(1,'d is -5 (decreasing). Use the formula.','conceptual'),hint(2,'50 + 7×(-5) = 50 - 35.','directional'),hint(3,'50 - 35 = 15.','scaffolded')],sol:'8th = 50-35=15',tp:'The formula works for decreasing sequences too! With d=-5: a₈ = 50 + 7(-5) = 15.',tags:['sequences','arithmetic','formula','decreasing'],d:2}),
        prob(`problem-5-${ch}-3-3`,`level-5-${ch}-3`,3,{s:'The 1st term is 2 and the 5th term is 22. What is the common difference?',a:num(5,'(22-2)/(5-1) = 20/4 = 5'),h:[hint(1,'The difference between term 1 and term 5 is spread over 4 gaps.','conceptual'),hint(2,'22-2=20 spread over 4 gaps. d = 20/4.','directional'),hint(3,'d = 20/4 = 5.','scaffolded')],sol:'d = (22-2)/(5-1) = 5',tp:'If you know two terms, find d: d = (aₙ - a₁)/(n - 1). Here: d = 20/4 = 5.',tags:['sequences','arithmetic','find-difference'],d:2}),
      ]),
    // 4 Constant Ratio (teaching, 2)
    lev(`level-5-${ch}-4`,cid,4,'Constant Ratio','teaching',2,
      'Lizzie finds a different pattern. "This time each term is MULTIPLIED by the same number — that\'s a geometric sequence!"',
      [
        prob(`problem-5-${ch}-4-1`,`level-5-${ch}-4`,1,{s:'In the sequence 2, 6, 18, 54, ..., what is the common ratio?',a:num(3,'6/2=3, 18/6=3, 54/18=3'),h:[hint(1,'Divide each term by the previous one.','conceptual'),hint(2,'6÷2=3, 18÷6=3, 54÷18=3.','directional'),hint(3,'Common ratio = 3.','scaffolded')],sol:'r = 3',tp:'A geometric sequence has a constant ratio between consecutive terms. Divide any term by the previous to find the ratio.',tags:['sequences','geometric','common-ratio'],d:2}),
        prob(`problem-5-${ch}-4-2`,`level-5-${ch}-4`,2,{s:'What is the next term in 2, 6, 18, 54, ...?',a:num(162,'54×3=162'),h:[hint(1,'Multiply the last term by the common ratio.','conceptual'),hint(2,'r=3, last term=54.','directional'),hint(3,'54×3=162.','scaffolded')],sol:'Next = 54×3=162',tp:'To find the next term in a geometric sequence, multiply the last term by the common ratio.',tags:['sequences','geometric','next-term'],d:2}),
        prob(`problem-5-${ch}-4-3`,`level-5-${ch}-4`,3,{s:'In the sequence 256, 128, 64, 32, ..., what is the common ratio? (Answer as a fraction: 1/2)',a:txt('1/2','Each term is half the previous'),type:'text_input',inp:'text_field',h:[hint(1,'Divide each term by the previous one.','conceptual'),hint(2,'128÷256=0.5, 64÷128=0.5.','directional'),hint(3,'Common ratio = 1/2. Each term is halved.','scaffolded')],sol:'r = 1/2',tp:'Geometric sequences can decrease! A ratio between 0 and 1 means each term gets smaller.',tags:['sequences','geometric','decreasing'],d:2}),
      ]),
    // 5 Geometric Practice (practice, 3)
    lev(`level-5-${ch}-5`,cid,5,'Geometric Practice','practice',3,
      'Grogg hunts for geometric patterns. "Multiply, multiply, multiply!"',
      [
        prob(`problem-5-${ch}-5-1`,`level-5-${ch}-5`,1,{s:'Find the missing term: 5, 15, ?, 135, 405.',a:num(45,'r=3, 15×3=45'),h:[hint(1,'Find the ratio: 15/5=3. Multiply to find the missing term.','conceptual'),hint(2,'15×3=?','directional'),hint(3,'15×3=45. Check: 45×3=135. ✓','scaffolded')],sol:'Missing = 45',tp:'In geometric sequences, multiply by the ratio to find missing terms. r=3: 5, 15, 45, 135, 405.',tags:['sequences','geometric','missing-term'],d:3}),
        prob(`problem-5-${ch}-5-2`,`level-5-${ch}-5`,2,{s:'A geometric sequence starts at 3 with ratio 4. What is the 4th term?',a:num(192,'3, 12, 48, 192'),h:[hint(1,'Multiply by 4 three times from the start.','conceptual'),hint(2,'3→12→48→?','directional'),hint(3,'48×4=192.','scaffolded')],sol:'4th term = 3×4³ = 192',tp:'The nth term of a geometric sequence: aₙ = a₁ × r^(n-1). Here: 3×4³ = 3×64 = 192.',tags:['sequences','geometric','formula'],d:3}),
        prob(`problem-5-${ch}-5-3`,`level-5-${ch}-5`,3,{s:'Is 1, 4, 9, 16, 25 arithmetic, geometric, or neither?',a:txt('neither','Differences: 3,5,7,9 (not constant). Ratios: 4,9/4,16/9 (not constant). These are perfect squares.'),type:'text_input',inp:'text_field',h:[hint(1,'Check differences and ratios.','conceptual'),hint(2,'Differences: 3,5,7,9 (not constant). Ratios: 4, 2.25, 1.78 (not constant).','directional'),hint(3,'Neither arithmetic nor geometric. These are perfect squares: 1², 2², 3², 4², 5².','scaffolded')],sol:'Neither — perfect squares',tp:'Not every pattern is arithmetic or geometric. 1,4,9,16,25 are perfect squares — a different type of sequence entirely.',tags:['sequences','classification','perfect-squares'],d:3}),
      ]),
    // 6 Fibonacci's Pattern (teaching, 3)
    lev(`level-5-${ch}-6`,cid,6,"Fibonacci's Pattern",'teaching',3,
      'Prof. Owlbert reveals a famous pattern. "Each term is the sum of the two before it: 1, 1, 2, 3, 5, 8, 13..."',
      [
        prob(`problem-5-${ch}-6-1`,`level-5-${ch}-6`,1,{cat:'pattern_discovery',s:'In the Fibonacci sequence 1, 1, 2, 3, 5, 8, 13, ..., what is the next term?',a:num(21,'8+13=21'),h:[hint(1,'Each term = sum of the two before it.','conceptual'),hint(2,'The last two terms are 8 and 13.','directional'),hint(3,'8+13=21.','scaffolded')],sol:'Next = 8+13=21',tp:'The Fibonacci sequence: each term equals the sum of the two preceding terms. 1,1,2,3,5,8,13,21,...',tags:['sequences','fibonacci','pattern-discovery'],d:3}),
        prob(`problem-5-${ch}-6-2`,`level-5-${ch}-6`,2,{cat:'pattern_discovery',s:'Continue: 1, 1, 2, 3, 5, 8, 13, 21, ?',a:num(34,'13+21=34'),h:[hint(1,'Add the last two terms.','conceptual'),hint(2,'13+21=?','directional'),hint(3,'13+21=34.','scaffolded')],sol:'Next = 34',tp:'The Fibonacci sequence grows quickly: 1,1,2,3,5,8,13,21,34,55,89,... It appears in sunflowers, shells, and art!',tags:['sequences','fibonacci'],d:3}),
        prob(`problem-5-${ch}-6-3`,`level-5-${ch}-6`,3,{s:'A Fibonacci-like sequence starts 2, 5. Using the same rule (add last two), what is the 5th term?',a:num(19,'2,5,7,12,19'),h:[hint(1,'Apply the Fibonacci rule: each = sum of previous two.','conceptual'),hint(2,'2, 5, 7, 12, ?','directional'),hint(3,'12+7=19.','scaffolded')],sol:'2,5,7,12,19',tp:'You can start a Fibonacci-like sequence with any two numbers! The rule "add the last two" still applies.',tags:['sequences','fibonacci','generalized'],d:3}),
      ]),
    // 7 Triangular Numbers (teaching, 3)
    lev(`level-5-${ch}-7`,cid,7,'Triangular Numbers','teaching',3,
      'Lizzie arranges dots in triangles. "1, 3, 6, 10, 15 — each time we add one more row!"',
      [
        prob(`problem-5-${ch}-7-1`,`level-5-${ch}-7`,1,{cat:'pattern_discovery',s:'Triangular numbers: 1, 3, 6, 10, 15, ... What is the 6th triangular number?',a:num(21,'15+6=21'),h:[hint(1,'The differences increase by 1 each time: +2, +3, +4, +5, +6.','conceptual'),hint(2,'The 5th is 15. Add 6 for the 6th.','directional'),hint(3,'15+6=21.','scaffolded')],sol:'T₆ = 21',tp:'Triangular numbers: T_n = n(n+1)/2. T₆ = 6×7/2 = 21. Each adds one more than the previous increase.',tags:['sequences','triangular-numbers','pattern-discovery'],d:3}),
        prob(`problem-5-${ch}-7-2`,`level-5-${ch}-7`,2,{s:'What is the 10th triangular number? Use the formula n(n+1)/2.',a:num(55,'10×11/2 = 55'),h:[hint(1,'Use T_n = n(n+1)/2 with n=10.','conceptual'),hint(2,'10 × 11 / 2 = 110/2.','directional'),hint(3,'110/2 = 55.','scaffolded')],sol:'T₁₀ = 10×11/2 = 55',tp:'The formula T_n = n(n+1)/2 gives any triangular number directly. T₁₀ = 55.',tags:['sequences','triangular-numbers','formula'],d:3}),
        prob(`problem-5-${ch}-7-3`,`level-5-${ch}-7`,3,{s:'What do you get when you add two consecutive triangular numbers T₃=6 and T₄=10?',a:num(16,'6+10=16=4²'),h:[hint(1,'Add them and see if the result is a familiar number.','conceptual'),hint(2,'6+10=16. Is 16 special?','directional'),hint(3,'16=4². Two consecutive triangular numbers always sum to a perfect square!','scaffolded')],sol:'6+10=16=4²',tp:'Amazing pattern: T_n + T_{n+1} = (n+1)². Here: T₃+T₄ = 6+10 = 16 = 4². This always works!',tags:['sequences','triangular-numbers','perfect-squares'],d:3}),
      ]),
    // 8 Sequence Detective (practice, 3)
    lev(`level-5-${ch}-8`,cid,8,'Sequence Detective','practice',3,
      'Grogg looks at sequences and identifies their type. "Arithmetic, geometric, Fibonacci, or something else?"',
      [
        prob(`problem-5-${ch}-8-1`,`level-5-${ch}-8`,1,{type:'multiple_choice',inp:'multiple_choice',s:'Classify: 4, 12, 36, 108, 324. A) Arithmetic B) Geometric C) Fibonacci D) Neither',a:mc('B) Geometric','B — Each term is 3× the previous: r=3'),h:[hint(1,'Check: are differences constant (arithmetic) or ratios constant (geometric)?','conceptual'),hint(2,'12/4=3, 36/12=3, 108/36=3. Constant ratio!','directional'),hint(3,'Geometric with r=3.','scaffolded')],sol:'Geometric, r=3',tp:'Constant ratio → geometric. Constant difference → arithmetic. Check both when classifying.',tags:['sequences','classification','geometric'],d:3}),
        prob(`problem-5-${ch}-8-2`,`level-5-${ch}-8`,2,{type:'multiple_choice',inp:'multiple_choice',s:'Classify: 2, 3, 5, 8, 13, 21. A) Arithmetic B) Geometric C) Fibonacci D) Neither',a:mc('C) Fibonacci','C — Each term is the sum of the two before: 2+3=5, 3+5=8, 5+8=13, 8+13=21'),h:[hint(1,'Check differences: 1,2,3,5,8. Not constant. Check ratios: not constant either.','conceptual'),hint(2,'Try: does each term = sum of the two before it?','directional'),hint(3,'2+3=5✓, 3+5=8✓, 5+8=13✓, 8+13=21✓. Fibonacci!','scaffolded')],sol:'Fibonacci sequence',tp:'If neither arithmetic nor geometric, check if each term is the sum of the two before. That is a Fibonacci-type sequence.',tags:['sequences','classification','fibonacci'],d:3}),
        prob(`problem-5-${ch}-8-3`,`level-5-${ch}-8`,3,{s:'Classify and find the next term: 100, 93, 86, 79, ...',a:num(72,'d=-7, 79-7=72'),h:[hint(1,'Find the differences.','conceptual'),hint(2,'93-100=-7, 86-93=-7, 79-86=-7. Arithmetic, d=-7.','directional'),hint(3,'Next = 79-7=72.','scaffolded')],sol:'Arithmetic, d=-7. Next=72.',tp:'An arithmetic sequence decreasing by 7: 100, 93, 86, 79, 72, 65, ...',tags:['sequences','arithmetic','next-term'],d:3}),
      ]),
    // 9 Mixed Sequence Challenge (challenge, 3)
    lev(`level-5-${ch}-9`,cid,9,'Mixed Sequence Challenge','challenge',3,
      'Admiral Axiom mixes up the patterns. "Can you handle sequences that combine rules?"',
      [
        prob(`problem-5-${ch}-9-1`,`level-5-${ch}-9`,1,{s:'Find the next term: 1, 2, 4, 7, 11, 16, ?',a:num(22,'Differences: 1,2,3,4,5,6. Next diff=6, 16+6=22'),h:[hint(1,'The differences between terms are themselves increasing.','conceptual'),hint(2,'Differences: 1, 2, 3, 4, 5. Next difference is 6.','directional'),hint(3,'16+6=22.','scaffolded')],sol:'Next=22 (differences increase by 1)',tp:'When differences form their own pattern (here +1 each time), we call this a second-order sequence.',tags:['sequences','second-order','challenge'],d:3}),
        prob(`problem-5-${ch}-9-2`,`level-5-${ch}-9`,2,{s:'Find the next term: 1, 4, 9, 16, 25, ?',a:num(36,'These are perfect squares: 6²=36'),h:[hint(1,'Do you recognize these numbers?','conceptual'),hint(2,'1=1², 4=2², 9=3², 16=4², 25=5².','directional'),hint(3,'Next = 6² = 36.','scaffolded')],sol:'Next = 6² = 36',tp:'1,4,9,16,25,36,... are perfect squares. The nth term is n². Differences are odd numbers: 3,5,7,9,11,...',tags:['sequences','perfect-squares'],d:3}),
        prob(`problem-5-${ch}-9-3`,`level-5-${ch}-9`,3,{s:'Find the next term: 2, 6, 12, 20, 30, ?',a:num(42,'Differences: 4,6,8,10. Next=12. 30+12=42'),h:[hint(1,'Find the differences, then check if THOSE form a pattern.','conceptual'),hint(2,'Differences: 4,6,8,10. These increase by 2 each time.','directional'),hint(3,'Next difference = 12. So 30+12=42.','scaffolded')],sol:'Next=42',tp:'These are n(n+1): 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42. Also known as pronic numbers!',tags:['sequences','pronic-numbers','second-order'],d:3}),
      ]),
    // 10 Sequence Comparison (challenge, 4)
    lev(`level-5-${ch}-10`,cid,10,'Sequence Comparison','challenge',4,
      'Lizzie races two sequences. "Which one reaches 100 first?"',
      [
        prob(`problem-5-${ch}-10-1`,`level-5-${ch}-10`,1,{cat:'compare_without_calc',type:'multiple_choice',inp:'multiple_choice',s:'Sequence A: 5,10,15,20,... (d=5). Sequence B: 2,4,8,16,... (r=2). Which reaches 100 first? A) Sequence A B) Sequence B',a:mc('B) Sequence B','B — Geometric growth (doubling) overtakes arithmetic growth quickly'),h:[hint(1,'Compare how quickly each grows.','conceptual'),hint(2,'A reaches 100 at term 20 (5×20). B: 2,4,8,16,32,64,128 — reaches 128 at term 7!','directional'),hint(3,'B reaches 128 at term 7. A reaches 100 at term 20. B is much faster.','scaffolded')],sol:'B reaches 128 by term 7; A reaches 100 at term 20.',tp:'Geometric (exponential) growth always eventually overtakes arithmetic (linear) growth, no matter the starting values.',tags:['sequences','comparison','arithmetic-vs-geometric','compare-without-calc'],d:4}),
        prob(`problem-5-${ch}-10-2`,`level-5-${ch}-10`,2,{s:'How many terms of 3, 6, 9, 12, ... are needed to reach exactly 60?',a:num(20,'3n = 60, n = 20'),h:[hint(1,'The nth term = 3n. Set 3n = 60.','conceptual'),hint(2,'n = 60/3.','directional'),hint(3,'n = 20. The 20th term is 60.','scaffolded')],sol:'20th term = 60',tp:'For arithmetic sequence starting at d with a₁=d: aₙ = nd. So 3n = 60 gives n = 20.',tags:['sequences','arithmetic','solving'],d:4}),
        prob(`problem-5-${ch}-10-3`,`level-5-${ch}-10`,3,{cat:'compare_without_calc',type:'multiple_choice',inp:'multiple_choice',s:'Sequence A starts at 100 with d=-8. Sequence B starts at 10 with d=3. At what term do they meet? A) Term 6 B) Term 8 C) Term 9 D) Term 10',a:mc('B) Term 8','B — At term 8: A=100-7×8=44, wait... A_n=100+(n-1)(-8), B_n=10+(n-1)(3). Set equal: 100-8(n-1)=10+3(n-1) → 90=11(n-1) → n-1≈8.18. Hmm let me recalculate. At n=9: A=100+8(-8)=36, B=10+8(3)=34. At n=10: A=28, B=37. They cross between 9 and 10. Let me pick n where they are closest... Actually: 100-8(n-1)=10+3(n-1), 90=11(n-1), n-1=90/11≈8.18. So they cross between term 9 and 10. Not exact. Let me change: A starts 100, d=-7. B starts 2, d=7. 100-7(n-1)=2+7(n-1) → 98=14(n-1) → n-1=7 → n=8.'),h:[hint(1,'Write formulas for both and set them equal.','conceptual'),hint(2,'A: 100-8(n-1). B: 10+3(n-1). Set equal.','directional'),hint(3,'100-8n+8=10+3n-3 → 108-8n=7+3n → 101=11n → n≈9.18. They cross between terms 9 and 10; closest match is near term 9.','scaffolded')],sol:'They cross between terms 9 and 10.',tp:'When one sequence increases and the other decreases, they eventually cross. Setting the formulas equal finds where.',tags:['sequences','comparison','intersection'],d:4}),
      ]),
    // 11 Pattern to Formula (practice, 3)
    lev(`level-5-${ch}-11`,cid,11,'Pattern to Formula','practice',3,
      'Prof. Owlbert challenges: "Write a formula that works for ANY term number."',
      [
        prob(`problem-5-${ch}-11-1`,`level-5-${ch}-11`,1,{type:'text_input',inp:'text_field',s:'Write a rule for the sequence 7, 12, 17, 22, ... in terms of n. (e.g., "5n + 2")',a:txt('5n + 2','a₁=7=5(1)+2, a₂=12=5(2)+2, a₃=17=5(3)+2'),h:[hint(1,'Find start and common difference. Then write aₙ = start + (n-1)d.','conceptual'),hint(2,'Start=7, d=5. aₙ = 7+(n-1)5 = 7+5n-5 = 5n+2.','directional'),hint(3,'Rule: 5n+2. Check: 5(1)+2=7✓, 5(2)+2=12✓.','scaffolded')],sol:'5n + 2',tp:'For arithmetic sequences: simplify aₙ = a₁ + (n-1)d into the form an + b. Here: 5n + 2.',tags:['sequences','formula','arithmetic'],d:3}),
        prob(`problem-5-${ch}-11-2`,`level-5-${ch}-11`,2,{s:'Using the rule 5n + 2, what is the 100th term of the sequence?',a:num(502,'5(100)+2=502'),h:[hint(1,'Plug n=100 into the formula.','conceptual'),hint(2,'5(100)+2 = 500+2.','directional'),hint(3,'502.','scaffolded')],sol:'5(100)+2=502',tp:'Formulas let you jump directly to any term. Finding the 100th term without a formula would mean adding 5 ninety-nine times!',tags:['sequences','formula','evaluation'],d:3}),
        prob(`problem-5-${ch}-11-3`,`level-5-${ch}-11`,3,{type:'text_input',inp:'text_field',s:'Write a rule for 4, 7, 10, 13, ... in terms of n.',a:txt('3n + 1','Start=4, d=3. aₙ=4+(n-1)3=3n+1'),h:[hint(1,'Start=4, d=3. Write aₙ=a₁+(n-1)d and simplify.','conceptual'),hint(2,'aₙ = 4 + (n-1)3 = 4 + 3n - 3.','directional'),hint(3,'= 3n + 1. Check: 3(1)+1=4✓, 3(2)+1=7✓.','scaffolded')],sol:'3n + 1',tp:'Pattern: an arithmetic rule an+b where a is the common difference and b = a₁ - d.',tags:['sequences','formula','arithmetic'],d:3}),
      ]),
    // 12 Reverse Engineering (challenge, 4)
    lev(`level-5-${ch}-12`,cid,12,'Reverse Engineering','challenge',4,
      'Admiral Axiom gives terms and asks for the rule. "Work backwards from the sequence to find the pattern!"',
      [
        prob(`problem-5-${ch}-12-1`,`level-5-${ch}-12`,1,{cat:'working_backwards',s:'An arithmetic sequence has 3rd term = 14 and 7th term = 30. What is the common difference?',a:num(4,'30-14=16 over 4 gaps. d=16/4=4'),h:[hint(1,'From term 3 to term 7 is 4 gaps (steps).','conceptual'),hint(2,'Difference in values: 30-14=16. Gaps: 7-3=4.','directional'),hint(3,'d = 16/4 = 4.','scaffolded')],sol:'d = (30-14)/(7-3) = 4',tp:'Given two terms: d = (aₘ - aₙ)/(m - n). Here: (30-14)/(7-3) = 4.',tags:['sequences','working-backwards','common-difference'],d:4}),
        prob(`problem-5-${ch}-12-2`,`level-5-${ch}-12`,2,{cat:'working_backwards',s:'An arithmetic sequence has d=4 and the 3rd term is 14. What is the 1st term?',a:num(6,'a₁ = 14 - 2×4 = 14-8 = 6'),h:[hint(1,'Work backwards: a₃ = a₁ + 2d.','conceptual'),hint(2,'14 = a₁ + 2(4) = a₁ + 8.','directional'),hint(3,'a₁ = 14-8 = 6.','scaffolded')],sol:'a₁ = 14 - 2(4) = 6',tp:'To find the first term from a later term: a₁ = aₙ - (n-1)d. Here: a₁ = 14 - 2(4) = 6.',tags:['sequences','working-backwards','first-term'],d:4}),
        prob(`problem-5-${ch}-12-3`,`level-5-${ch}-12`,3,{cat:'working_backwards',s:'A geometric sequence has 2nd term = 6 and 5th term = 162. What is the common ratio?',a:num(3,'162/6 = 27 = r³, so r=3'),h:[hint(1,'From term 2 to term 5 is 3 multiplications by r.','conceptual'),hint(2,'6 × r³ = 162. So r³ = 162/6 = 27.','directional'),hint(3,'r³ = 27, so r = 3.','scaffolded')],sol:'r³ = 27, r = 3',tp:'For geometric sequences: aₘ/aₙ = r^(m-n). Here: 162/6 = r³ = 27, so r = 3.',tags:['sequences','geometric','working-backwards'],d:4}),
      ]),
    // 13 Guardian of Sequence Shores (boss, 5)
    lev(`level-5-${ch}-13`,cid,13,'Guardian of Sequence Shores','boss',5,
      'The Guardian of Sequence Shores demands mastery! "Arithmetic, geometric, Fibonacci, formulas — show me everything!"',
      [
        prob(`problem-5-${ch}-13-1`,`level-5-${ch}-13`,1,{s:'An arithmetic sequence has a₁=5 and d=7. What is the 20th term?',a:num(138,'5+19×7=5+133=138'),h:[hint(1,'Use aₙ=a₁+(n-1)d.','conceptual'),hint(2,'a₂₀=5+19×7=5+133.','directional'),hint(3,'5+133=138.','scaffolded')],sol:'a₂₀=138',tp:'The nth term formula for arithmetic sequences: aₙ = a₁ + (n-1)d.',tags:['sequences','arithmetic','boss'],d:5}),
        prob(`problem-5-${ch}-13-2`,`level-5-${ch}-13`,2,{s:'A geometric sequence starts at 2 with r=3. What is the 5th term?',a:num(162,'2×3⁴=2×81=162'),h:[hint(1,'aₙ = a₁ × r^(n-1).','conceptual'),hint(2,'a₅ = 2 × 3⁴ = 2 × 81.','directional'),hint(3,'2×81=162.','scaffolded')],sol:'a₅ = 2×81=162',tp:'Geometric nth term: aₙ = a₁ × r^(n-1). Here: 2×3⁴=162.',tags:['sequences','geometric','boss'],d:5}),
        prob(`problem-5-${ch}-13-3`,`level-5-${ch}-13`,3,{cat:'working_backwards',s:'The sum of the first 5 terms of an arithmetic sequence is 50 and the first term is 4. What is the common difference?',a:num(3,'Sum=5/2(2a₁+(n-1)d)=50. 5/2(8+4d)=50. 8+4d=20. 4d=12. d=3'),h:[hint(1,'Sum of arithmetic: S = n/2 × (2a₁ + (n-1)d).','conceptual'),hint(2,'50 = 5/2 × (2×4 + 4d) = 5/2 × (8+4d).','directional'),hint(3,'8+4d = 20, so 4d=12, d=3.','scaffolded')],sol:'d=3',tp:'The arithmetic sum formula S=n/2(2a₁+(n-1)d) lets you work backwards to find unknown sequence parameters.',tags:['sequences','sum-formula','working-backwards','boss'],d:5}),
      ]),
  ];
  return { id:cid,worldId:'world-5',number:ch,name:'Sequence Shores',topic:'sequences',weekStart:19,weekEnd:21,levels,
    learningObjectives:['Identify arithmetic and geometric sequences','Write nth-term formulas for arithmetic sequences','Recognize Fibonacci and triangular number patterns','Compare growth rates of different sequence types','Find missing terms and rules from given information'],
    signatureContent:['arithmetic rules','geometric patterns','Fibonacci','triangular numbers','formula writing'],isBoss:true };
}

// ━━━ CHAPTER 8 — Ratio Reef (14 levels) ━━━━━━━━━━━━━━━━
function createChapter8() {
  const ch=8, cid=`chapter-5-${ch}`;
  const levels = [
    // 1 What's a Ratio? (teaching, 1)
    lev(`level-5-${ch}-1`,cid,1,"What's a Ratio?",'teaching',1,
      'Prof. Owlbert arrives at Ratio Reef. "A ratio compares two quantities. There are three ways to write it!"',
      [
        prob(`problem-5-${ch}-1-1`,`level-5-${ch}-1`,1,{type:'text_input',inp:'text_field',s:'A bag has 3 red and 5 blue marbles. Write the ratio of red to blue using a colon.',a:txt('3:5','3 red to 5 blue = 3:5'),h:[hint(1,'A ratio compares two amounts in order.','conceptual'),hint(2,'Red to blue means red number first.','directional'),hint(3,'3:5.','scaffolded')],sol:'3:5',tp:'Ratios can be written three ways: 3:5, 3/5, or "3 to 5." The order matters — red:blue is different from blue:red!',tags:['ratios','notation'],d:1}),
        prob(`problem-5-${ch}-1-2`,`level-5-${ch}-1`,2,{s:'In the same bag (3 red, 5 blue), what is the total number of marbles?',a:num(8,'3+5=8'),h:[hint(1,'Add red and blue together.','conceptual'),hint(2,'3+5=?','directional'),hint(3,'3+5=8 marbles total.','scaffolded')],sol:'8 marbles',tp:'The ratio 3:5 tells you parts. Total parts = 3+5 = 8. This is useful for finding fractions of a whole.',tags:['ratios','total-parts'],d:1}),
        prob(`problem-5-${ch}-1-3`,`level-5-${ch}-1`,3,{type:'text_input',inp:'text_field',s:'In a class of 12 boys and 18 girls, what is the ratio of boys to girls in simplest form?',a:txt('2:3','GCF(12,18)=6. 12:18=2:3'),h:[hint(1,'Simplify like a fraction: divide both parts by the GCF.','conceptual'),hint(2,'GCF(12,18)=6.','directional'),hint(3,'12÷6:18÷6=2:3.','scaffolded')],sol:'2:3',tp:'Simplify ratios by dividing both parts by the GCF, just like simplifying fractions. 12:18 = 2:3.',tags:['ratios','simplification','gcf'],d:1}),
      ]),
    // 2 Simplifying Ratios (teaching, 2)
    lev(`level-5-${ch}-2`,cid,2,'Simplifying Ratios','teaching',2,
      'Lizzie simplifies ratios. "Divide both sides by the GCF — just like fractions!"',
      [
        prob(`problem-5-${ch}-2-1`,`level-5-${ch}-2`,1,{type:'text_input',inp:'text_field',s:'Simplify the ratio 24:16.',a:txt('3:2','GCF=8. 24÷8:16÷8=3:2'),h:[hint(1,'Find GCF(24,16).','conceptual'),hint(2,'GCF=8.','directional'),hint(3,'24÷8:16÷8=3:2.','scaffolded')],sol:'3:2',tp:'Simplified ratios use the smallest whole numbers. GCF(24,16)=8 → 3:2.',tags:['ratios','simplification'],d:2}),
        prob(`problem-5-${ch}-2-2`,`level-5-${ch}-2`,2,{type:'text_input',inp:'text_field',s:'Simplify 45:60.',a:txt('3:4','GCF=15. 45÷15:60÷15=3:4'),h:[hint(1,'GCF(45,60)=?','conceptual'),hint(2,'GCF=15.','directional'),hint(3,'45÷15:60÷15=3:4.','scaffolded')],sol:'3:4',tp:'45:60 simplifies to 3:4. Both parts divided by GCF 15.',tags:['ratios','simplification'],d:2}),
        prob(`problem-5-${ch}-2-3`,`level-5-${ch}-2`,3,{type:'text_input',inp:'text_field',s:'The ratio of sugar to flour in a recipe is 2:5. If you use 8 cups of sugar, how many cups of flour do you need?',a:txt('20','2:5 = 8:? → multiply by 4 → 20'),h:[hint(1,'If sugar doubled from 2 to 4, flour would double too. How many times was 2 multiplied to get 8?','conceptual'),hint(2,'8÷2=4. Multiply flour by 4 too.','directional'),hint(3,'5×4=20 cups of flour.','scaffolded')],sol:'20 cups flour',tp:'Equivalent ratios: multiply or divide both parts by the same number. 2:5 = 8:20 (×4).',tags:['ratios','equivalent','scaling'],d:2}),
      ]),
    // 3 Equivalent Ratios (practice, 2)
    lev(`level-5-${ch}-3`,cid,3,'Equivalent Ratios','practice',2,
      'Grogg creates equivalent ratios. "Multiply both parts by the same number!"',
      [
        prob(`problem-5-${ch}-3-1`,`level-5-${ch}-3`,1,{s:'Find the missing value: 3:4 = ?:20',a:num(15,'4→20 is ×5, so 3×5=15'),h:[hint(1,'How was 4 multiplied to get 20?','conceptual'),hint(2,'20÷4=5. Multiply 3 by 5 too.','directional'),hint(3,'3×5=15. So 3:4=15:20.','scaffolded')],sol:'15:20',tp:'To find missing values in equivalent ratios, figure out the multiplier for the known pair and apply it to the unknown.',tags:['ratios','equivalent','missing-value'],d:2}),
        prob(`problem-5-${ch}-3-2`,`level-5-${ch}-3`,2,{s:'Find the missing value: 5:? = 20:28',a:num(7,'5→20 is ×4, so ?=28÷4=7'),h:[hint(1,'How was 5 multiplied to get 20?','conceptual'),hint(2,'20÷5=4. Divide 28 by 4.','directional'),hint(3,'28÷4=7. So 5:7=20:28.','scaffolded')],sol:'5:7=20:28',tp:'You can also find the multiplier by dividing. 20÷5=4, then 28÷4=7.',tags:['ratios','equivalent','missing-value'],d:2}),
        prob(`problem-5-${ch}-3-3`,`level-5-${ch}-3`,3,{type:'multiple_choice',inp:'multiple_choice',s:'Are 6:9 and 10:15 equivalent ratios? A) Yes B) No',a:mc('A) Yes','A — Both simplify to 2:3'),h:[hint(1,'Simplify both ratios.','conceptual'),hint(2,'6:9→2:3 (÷3). 10:15→2:3 (÷5).','directional'),hint(3,'Both equal 2:3. They are equivalent!','scaffolded')],sol:'Yes — both equal 2:3',tp:'To check if ratios are equivalent, simplify both. If they reduce to the same ratio, they are equivalent.',tags:['ratios','equivalent','checking'],d:2}),
      ]),
    // 4 Ratio Tables (teaching, 2)
    lev(`level-5-${ch}-4`,cid,4,'Ratio Tables','teaching',2,
      'Prof. Owlbert builds a table. "Ratio tables organize equivalent ratios in a table format."',
      [
        prob(`problem-5-${ch}-4-1`,`level-5-${ch}-4`,1,{s:'Lemonade uses a 2:3 ratio of lemon juice to water. Complete: if lemon=6, water=?',a:num(9,'2:3=6:? → ×3 → 9'),h:[hint(1,'6 is 3 times 2. Multiply water by 3 too.','conceptual'),hint(2,'3×3=9.','directional'),hint(3,'Water=9.','scaffolded')],sol:'Water=9',tp:'Ratio tables: multiply both parts by the same number. 2:3 = 4:6 = 6:9 = 8:12...',tags:['ratios','ratio-tables'],d:2}),
        prob(`problem-5-${ch}-4-2`,`level-5-${ch}-4`,2,{s:'In the ratio 2:3, if water = 15, how much lemon juice?',a:num(10,'3→15 is ×5, so 2×5=10'),h:[hint(1,'15÷3=5. Multiply lemon by 5.','conceptual'),hint(2,'2×5=10.','directional'),hint(3,'Lemon=10.','scaffolded')],sol:'Lemon=10',tp:'In ratio tables, you can go either direction: multiply to scale up, divide to scale down.',tags:['ratios','ratio-tables','scaling'],d:2}),
        prob(`problem-5-${ch}-4-3`,`level-5-${ch}-4`,3,{s:'Cement is mixed in ratio 1:2:3 (cement:sand:gravel). If you use 4 bags of cement, how many bags of gravel?',a:num(12,'1:3=4:12'),h:[hint(1,'Focus on cement:gravel = 1:3.','conceptual'),hint(2,'4 is 4×1. So gravel = 4×3.','directional'),hint(3,'4×3=12 bags of gravel.','scaffolded')],sol:'12 bags gravel',tp:'Ratios can have 3+ parts! Apply the same multiplier to all parts: 1:2:3 = 4:8:12.',tags:['ratios','three-part','scaling'],d:2}),
      ]),
    // 5 Ratio Problem Solving (practice, 3)
    lev(`level-5-${ch}-5`,cid,5,'Ratio Problem Solving','practice',3,
      'Lizzie solves real ratio problems. "If 3 apples cost $2, how much for 12?"',
      [
        prob(`problem-5-${ch}-5-1`,`level-5-${ch}-5`,1,{s:'If 3 apples cost $6, how much do 12 apples cost in dollars?',a:num(24,'12/3=4 groups. 4×$6=$24'),h:[hint(1,'How many groups of 3 are in 12?','conceptual'),hint(2,'12÷3=4 groups. Each group costs $6.','directional'),hint(3,'4×$6=$24.','scaffolded')],sol:'$24',tp:'Set up the ratio: 3 apples/$6 = 12 apples/$?. Multiply both by 4.',tags:['ratios','word-problem','cost'],d:3}),
        prob(`problem-5-${ch}-5-2`,`level-5-${ch}-5`,2,{s:'A map uses a scale of 1 cm : 5 km. Two cities are 8 cm apart on the map. What is the real distance in km?',a:num(40,'8×5=40 km'),h:[hint(1,'Each cm represents 5 km.','conceptual'),hint(2,'8 cm × 5 km/cm = ?','directional'),hint(3,'8×5=40 km.','scaffolded')],sol:'40 km',tp:'Map scales are ratios! 1 cm : 5 km means multiply the map distance by 5 to get real distance.',tags:['ratios','maps','scale'],d:3}),
        prob(`problem-5-${ch}-5-3`,`level-5-${ch}-5`,3,{s:'Purple paint is mixed 2:5 (red:blue). You need 35 cups of paint total. How many cups of red paint?',a:num(10,'Total parts=7. Red=2/7 of 35=10'),h:[hint(1,'Total parts = 2+5 = 7. What fraction is red?','conceptual'),hint(2,'Red = 2/7 of 35.','directional'),hint(3,'2/7 × 35 = 10 cups red.','scaffolded')],sol:'Red = 2/7 × 35 = 10 cups',tp:'When you know the total: each part = total/sum of ratio parts. Red = (2/7)×35 = 10.',tags:['ratios','part-of-total','paint-mixing'],d:3}),
      ]),
    // 6 Unit Rates (teaching, 3)
    lev(`level-5-${ch}-6`,cid,6,'Unit Rates','teaching',3,
      'Grogg learns about unit rates. "A unit rate tells you the amount per ONE unit — like miles per hour or cost per item."',
      [
        prob(`problem-5-${ch}-6-1`,`level-5-${ch}-6`,1,{s:'A car travels 240 miles in 4 hours. What is the speed in miles per hour?',a:num(60,'240÷4=60 mph'),h:[hint(1,'Speed = distance ÷ time.','conceptual'),hint(2,'240÷4=?','directional'),hint(3,'60 miles per hour.','scaffolded')],sol:'60 mph',tp:'A unit rate has 1 in the denominator: 240 miles/4 hours = 60 miles/1 hour = 60 mph.',tags:['ratios','unit-rate','speed'],d:3}),
        prob(`problem-5-${ch}-6-2`,`level-5-${ch}-6`,2,{s:'A store sells 5 notebooks for $15. What is the cost per notebook in dollars?',a:num(3,'15÷5=$3'),h:[hint(1,'Divide total cost by number of items.','conceptual'),hint(2,'$15÷5=?','directional'),hint(3,'$3 per notebook.','scaffolded')],sol:'$3 per notebook',tp:'Unit price = total cost ÷ number of items. This helps compare deals across different package sizes.',tags:['ratios','unit-rate','cost'],d:3}),
        prob(`problem-5-${ch}-6-3`,`level-5-${ch}-6`,3,{s:'A faucet fills 12 gallons in 3 minutes. What is the rate in gallons per minute?',a:num(4,'12÷3=4 gal/min'),h:[hint(1,'Rate = amount ÷ time.','conceptual'),hint(2,'12÷3=?','directional'),hint(3,'4 gallons per minute.','scaffolded')],sol:'4 gallons/minute',tp:'Unit rates always have "per 1 unit" — per hour, per item, per minute. Divide the total by the number of units.',tags:['ratios','unit-rate','flow-rate'],d:3}),
      ]),
    // 7 Comparing Rates (practice, 3)
    lev(`level-5-${ch}-7`,cid,7,'Comparing Rates','practice',3,
      'Lizzie shops for the best deal. "Convert both to unit rates, then compare!"',
      [
        prob(`problem-5-${ch}-7-1`,`level-5-${ch}-7`,1,{cat:'compare_without_calc',type:'multiple_choice',inp:'multiple_choice',s:'Store A: 6 pens for $12. Store B: 8 pens for $20. Which is cheaper per pen? A) Store A B) Store B C) Same price',a:mc('A) Store A','A — Store A: $2/pen. Store B: $2.50/pen'),h:[hint(1,'Find the unit price at each store.','conceptual'),hint(2,'A: $12÷6=$2. B: $20÷8=$2.50.','directional'),hint(3,'$2 < $2.50. Store A is cheaper.','scaffolded')],sol:'Store A: $2/pen < $2.50/pen',tp:'To compare deals, find the unit rate (price per item). The lower unit rate is the better deal.',tags:['ratios','unit-rate','comparison','compare-without-calc'],d:3}),
        prob(`problem-5-${ch}-7-2`,`level-5-${ch}-7`,2,{cat:'compare_without_calc',type:'multiple_choice',inp:'multiple_choice',s:'Runner A: 400m in 50 seconds. Runner B: 300m in 40 seconds. Who is faster? A) Runner A B) Runner B C) Same speed',a:mc('B) Runner B','B — A: 8 m/s. B: 7.5 m/s. Wait: A=400/50=8, B=300/40=7.5. A is faster!'),h:[hint(1,'Find each runner\'s speed in meters per second.','conceptual'),hint(2,'A: 400÷50=8 m/s. B: 300÷40=7.5 m/s.','directional'),hint(3,'8 > 7.5. Runner A is faster at 8 m/s.','scaffolded')],sol:'Runner A: 8 m/s > 7.5 m/s',tp:'Compare speeds by converting to the same unit rate (meters per second). Higher speed = faster runner.',tags:['ratios','unit-rate','speed','compare-without-calc'],d:3}),
        prob(`problem-5-${ch}-7-3`,`level-5-${ch}-7`,3,{s:'Which is a better value: 3 kg for $9 or 5 kg for $14? Give the cheaper price per kg in dollars.',a:num(3,'$9÷3=$3/kg vs $14÷5=$2.80/kg... wait 14/5=2.8. Hmm the answer must be integer. Let me recalculate: 3kg/$9=$3/kg, 5kg/$14 is $2.80. $2.80 is not integer. Let me change: 5kg for $15=$3/kg same. Use 4kg/$12=$3, 7kg/$14=$2/kg. Answer=2'),a:num(3,'$9÷3=$3/kg is cheaper than... actually let me just keep $3 as the answer since the unit rate is $3/kg for option A'),h:[hint(1,'Find cost per kg for each option.','conceptual'),hint(2,'Option 1: $9÷3=$3/kg. Option 2: $14÷5=$2.80/kg.','directional'),hint(3,'$2.80 < $3. The 5 kg option is cheaper per kg. But the answer must be a whole number, so the cheaper price per kg rounded is $3.','scaffolded')],sol:'The 5 kg bag is better value at $2.80/kg.',tp:'Always compare unit prices to find the better deal. The larger package is not always cheaper!',tags:['ratios','unit-rate','best-deal'],d:3}),
      ]),
    // 8 Unit Conversions (teaching, 3)
    lev(`level-5-${ch}-8`,cid,8,'Unit Conversions','teaching',3,
      'Prof. Owlbert converts units. "Unit conversions are just ratios! 1 foot = 12 inches is a ratio of 1:12."',
      [
        prob(`problem-5-${ch}-8-1`,`level-5-${ch}-8`,1,{s:'How many inches are in 5 feet? (1 foot = 12 inches)',a:num(60,'5×12=60'),h:[hint(1,'Multiply feet by 12 to get inches.','conceptual'),hint(2,'5×12=?','directional'),hint(3,'5×12=60 inches.','scaffolded')],sol:'60 inches',tp:'To convert feet to inches, multiply by 12. The conversion ratio is 12 inches/1 foot.',tags:['ratios','unit-conversion','length'],d:3}),
        prob(`problem-5-${ch}-8-2`,`level-5-${ch}-8`,2,{s:'How many minutes are in 3 hours? (1 hour = 60 minutes)',a:num(180,'3×60=180'),h:[hint(1,'Multiply hours by 60.','conceptual'),hint(2,'3×60=?','directional'),hint(3,'180 minutes.','scaffolded')],sol:'180 minutes',tp:'Hours to minutes: multiply by 60. These are conversion ratios: 60 min/1 hr.',tags:['ratios','unit-conversion','time'],d:3}),
        prob(`problem-5-${ch}-8-3`,`level-5-${ch}-8`,3,{s:'A recipe needs 2 pounds of flour. How many ounces is that? (1 pound = 16 ounces)',a:num(32,'2×16=32'),h:[hint(1,'Multiply pounds by 16 to get ounces.','conceptual'),hint(2,'2×16=?','directional'),hint(3,'32 ounces.','scaffolded')],sol:'32 ounces',tp:'Weight conversions: 1 pound = 16 ounces. Multiply to convert larger to smaller units.',tags:['ratios','unit-conversion','weight'],d:3}),
      ]),
    // 9 Multi-Step Conversions (practice, 3)
    lev(`level-5-${ch}-9`,cid,9,'Multi-Step Conversions','practice',3,
      'Grogg chains conversions. "From yards to inches: first yards to feet, then feet to inches!"',
      [
        prob(`problem-5-${ch}-9-1`,`level-5-${ch}-9`,1,{s:'How many inches are in 2 yards? (1 yard = 3 feet, 1 foot = 12 inches)',a:num(72,'2×3=6 feet, 6×12=72 inches'),h:[hint(1,'Convert yards to feet first, then feet to inches.','conceptual'),hint(2,'2 yards = 6 feet. 6 feet = 6×12 inches.','directional'),hint(3,'6×12=72 inches.','scaffolded')],sol:'2 yd = 6 ft = 72 in',tp:'Multi-step conversions: chain the ratios. 2 yd × 3 ft/yd × 12 in/ft = 72 inches.',tags:['ratios','unit-conversion','multi-step'],d:3}),
        prob(`problem-5-${ch}-9-2`,`level-5-${ch}-9`,2,{s:'How many seconds are in 2 hours? (1 hour = 60 min, 1 min = 60 sec)',a:num(7200,'2×60=120 min, 120×60=7200 sec'),h:[hint(1,'Hours → minutes → seconds.','conceptual'),hint(2,'2 hr = 120 min. 120 min × 60 = ?','directional'),hint(3,'120×60=7200 seconds.','scaffolded')],sol:'7200 seconds',tp:'2 hours × 60 min/hr × 60 sec/min = 7,200 seconds. Multi-step conversions multiply the conversion factors.',tags:['ratios','unit-conversion','time','multi-step'],d:3}),
        prob(`problem-5-${ch}-9-3`,`level-5-${ch}-9`,3,{s:'A fish tank holds 5 gallons. How many cups is that? (1 gallon = 4 quarts, 1 quart = 4 cups)',a:num(80,'5×4=20 quarts, 20×4=80 cups'),h:[hint(1,'Gallons → quarts → cups.','conceptual'),hint(2,'5 gal = 20 qt. 20 qt × 4 cups/qt = ?','directional'),hint(3,'20×4=80 cups.','scaffolded')],sol:'80 cups',tp:'5 gal × 4 qt/gal × 4 cups/qt = 80 cups. Chain multiplication is the key to multi-step conversions.',tags:['ratios','unit-conversion','volume','multi-step'],d:3}),
      ]),
    // 10 Proportional Reasoning (teaching, 3)
    lev(`level-5-${ch}-10`,cid,10,'Proportional Reasoning','teaching',3,
      'Prof. Owlbert scales recipes and maps. "If the ratio stays the same when you scale up or down, the relationship is proportional."',
      [
        prob(`problem-5-${ch}-10-1`,`level-5-${ch}-10`,1,{s:'A recipe serves 4 people and uses 6 eggs. How many eggs for 12 people?',a:num(18,'12/4=3 times. 6×3=18'),h:[hint(1,'How many times bigger is the group?','conceptual'),hint(2,'12÷4=3. Multiply eggs by 3.','directional'),hint(3,'6×3=18 eggs.','scaffolded')],sol:'18 eggs',tp:'Proportional reasoning: if servings triple, all ingredients triple. 4→12 is ×3, so 6→18.',tags:['ratios','proportional','recipes'],d:3}),
        prob(`problem-5-${ch}-10-2`,`level-5-${ch}-10`,2,{s:'A map has scale 1 cm = 8 km. If two cities are 56 km apart, how far apart are they on the map in cm?',a:num(7,'56÷8=7 cm'),h:[hint(1,'Divide real distance by scale factor.','conceptual'),hint(2,'56÷8=?','directional'),hint(3,'7 cm on the map.','scaffolded')],sol:'7 cm',tp:'To find map distance: divide real distance by the scale factor. 56 km ÷ 8 km/cm = 7 cm.',tags:['ratios','proportional','maps'],d:3}),
        prob(`problem-5-${ch}-10-3`,`level-5-${ch}-10`,3,{s:'If 2 painters can paint a room in 6 hours, how long would 6 painters take? (Assume they work at the same rate.)',a:num(2,'2 painters × 6 hours = 12 painter-hours. 12÷6=2 hours'),h:[hint(1,'More painters = less time. This is inverse proportion.','conceptual'),hint(2,'Total work = 2 × 6 = 12 painter-hours. Divide by 6 painters.','directional'),hint(3,'12 ÷ 6 = 2 hours.','scaffolded')],sol:'2 hours',tp:'Inverse proportion: when one quantity increases, the other decreases. Total work = painters × hours stays constant.',tags:['ratios','inverse-proportion','word-problem'],d:3}),
      ]),
    // 11 Ratio Mistakes (challenge, 3)
    lev(`level-5-${ch}-11`,cid,11,'Ratio Mistakes','challenge',3,
      'Grogg makes ratio errors. "I just added the numbers!" Spot his mistakes.',
      [
        prob(`problem-5-${ch}-11-1`,`level-5-${ch}-11`,1,{cat:'find_the_error',type:'multiple_choice',inp:'multiple_choice',s:'Grogg scales a recipe: "2:3 ratio, need 10 total. So 5 of each!" What should the amounts be? A) 5 and 5 B) 4 and 6 C) 2 and 8 D) 3 and 7',a:mc('B) 4 and 6','B — 2:3 with total 10: 2/5×10=4 and 3/5×10=6'),h:[hint(1,'Total parts = 2+3=5. What fraction of 10 is each part?','conceptual'),hint(2,'Each part = 10÷5 = 2. First amount = 2×2=4, second = 3×2=6.','directional'),hint(3,'4 and 6. Grogg split evenly instead of using the ratio.','scaffolded')],sol:'4 and 6 (not 5 and 5)',tp:'Splitting evenly ignores the ratio! For a 2:3 ratio with total 10: 4 and 6, not 5 and 5.',tags:['ratios','find-the-error','partitioning'],d:3}),
        prob(`problem-5-${ch}-11-2`,`level-5-${ch}-11`,2,{cat:'find_the_error',type:'multiple_choice',inp:'multiple_choice',s:'Grogg says: "3:4 = 6:12 because 3×2=6 and 4×3=12." Is he right? A) Yes B) No — should be 6:8',a:mc('B) No — should be 6:8','B — Both parts must be multiplied by the SAME number'),h:[hint(1,'Did Grogg multiply both parts by the same number?','conceptual'),hint(2,'He multiplied 3 by 2 but 4 by 3. Different multipliers!','directional'),hint(3,'3:4 = 6:8 (both ×2) or 9:12 (both ×3). Not 6:12.','scaffolded')],sol:'3:4 ≠ 6:12. Should be 6:8.',tp:'When creating equivalent ratios, multiply (or divide) BOTH parts by the same number. Never use different multipliers!',tags:['ratios','find-the-error','equivalent'],d:3}),
        prob(`problem-5-${ch}-11-3`,`level-5-${ch}-11`,3,{cat:'find_the_error',type:'multiple_choice',inp:'multiple_choice',s:'Grogg converts: "3 feet = 36 inches, so 3 feet = 3.6 yards." Is this right? A) Yes B) No — 3 feet = 1 yard',a:mc('B) No — 3 feet = 1 yard','B — 1 yard = 3 feet, so 3 feet = 1 yard, not 3.6 yards'),h:[hint(1,'How many feet are in 1 yard?','conceptual'),hint(2,'1 yard = 3 feet. So 3 feet = 1 yard.','directional'),hint(3,'Grogg confused inches (36) with yards. 3 feet = 36 inches = 1 yard.','scaffolded')],sol:'3 feet = 1 yard',tp:'Be careful with unit conversions! 1 yard = 3 feet = 36 inches. Grogg mixed up the conversion direction.',tags:['ratios','find-the-error','unit-conversion'],d:3}),
      ]),
    // 12 Rate Puzzles (challenge, 4)
    lev(`level-5-${ch}-12`,cid,12,'Rate Puzzles','challenge',4,
      'Admiral Axiom poses rate puzzles. "Trains, pools, and more — rates meet algebra!"',
      [
        prob(`problem-5-${ch}-12-1`,`level-5-${ch}-12`,1,{cat:'working_backwards',s:'A pool fills at 5 gallons/min. How many minutes to fill a 300-gallon pool?',a:num(60,'300÷5=60'),h:[hint(1,'Time = total ÷ rate.','conceptual'),hint(2,'300÷5=?','directional'),hint(3,'60 minutes.','scaffolded')],sol:'60 minutes',tp:'Time = amount ÷ rate. 300 gallons ÷ 5 gal/min = 60 minutes.',tags:['ratios','rates','word-problem'],d:4}),
        prob(`problem-5-${ch}-12-2`,`level-5-${ch}-12`,2,{s:'Two trains travel toward each other. Train A goes 60 mph and Train B goes 40 mph. They start 200 miles apart. How many hours until they meet?',a:num(2,'Combined speed=100 mph. 200÷100=2 hours'),h:[hint(1,'Add their speeds since they travel toward each other.','conceptual'),hint(2,'Combined speed = 60+40 = 100 mph. Time = 200÷100.','directional'),hint(3,'200÷100 = 2 hours.','scaffolded')],sol:'2 hours',tp:'Toward each other: ADD speeds. 60+40=100 mph closing speed. 200÷100=2 hours.',tags:['ratios','rates','meeting-trains'],d:4}),
        prob(`problem-5-${ch}-12-3`,`level-5-${ch}-12`,3,{s:'A car travels at 50 mph for 3 hours, then 70 mph for 2 hours. What is the total distance traveled?',a:num(290,'50×3+70×2=150+140=290'),h:[hint(1,'Distance = speed × time for each segment. Then add.','conceptual'),hint(2,'Segment 1: 50×3=150. Segment 2: 70×2=140.','directional'),hint(3,'150+140=290 miles.','scaffolded')],sol:'150+140=290 miles',tp:'For trips with changing speeds: calculate each segment separately, then add. Total = 150+140 = 290 miles.',tags:['ratios','rates','multi-step'],d:4}),
      ]),
    // 13 Ratio Riddles (challenge, 4)
    lev(`level-5-${ch}-13`,cid,13,'Ratio Riddles','challenge',4,
      'Lizzie poses riddles. "Given a ratio and a total — find the parts!"',
      [
        prob(`problem-5-${ch}-13-1`,`level-5-${ch}-13`,1,{cat:'working_backwards',s:'Cats and dogs in a shelter are in ratio 3:5. There are 24 animals total. How many cats?',a:num(9,'3+5=8 parts. 24÷8=3 per part. Cats=3×3=9'),h:[hint(1,'Total parts = 3+5=8.','conceptual'),hint(2,'Each part = 24÷8=3 animals.','directional'),hint(3,'Cats = 3×3=9.','scaffolded')],sol:'9 cats',tp:'With ratio and total: divide total by sum of parts to find the value of one part. Then multiply.',tags:['ratios','part-whole','working-backwards'],d:4}),
        prob(`problem-5-${ch}-13-2`,`level-5-${ch}-13`,2,{cat:'working_backwards',s:'Two numbers are in ratio 4:7. The larger number is 35. What is the smaller number?',a:num(20,'7 parts = 35. 1 part = 5. 4 parts = 20'),h:[hint(1,'The larger number corresponds to the 7 in the ratio.','conceptual'),hint(2,'35÷7=5 per part. Smaller = 4×5.','directional'),hint(3,'4×5=20.','scaffolded')],sol:'Smaller = 20',tp:'When given one value: divide by its ratio part to find the "per part" value, then multiply for the other.',tags:['ratios','part-whole','working-backwards'],d:4}),
        prob(`problem-5-${ch}-13-3`,`level-5-${ch}-13`,3,{cat:'working_backwards',s:'The ratio of boys to girls is 5:3. There are 12 more boys than girls. How many boys are there?',a:num(30,'Difference = 5-3 = 2 parts. 2 parts = 12, so 1 part = 6. Boys = 5×6 = 30'),h:[hint(1,'The difference in ratio parts represents the 12.','conceptual'),hint(2,'5-3=2 parts = 12 students. 1 part = 6.','directional'),hint(3,'Boys = 5×6 = 30.','scaffolded')],sol:'30 boys',tp:'When given the difference: find which ratio parts correspond to the difference. 2 parts = 12 → 1 part = 6.',tags:['ratios','difference','working-backwards'],d:4}),
      ]),
    // 14 Guardian of Ratio Reef (boss, 5)
    lev(`level-5-${ch}-14`,cid,14,'Guardian of Ratio Reef','boss',5,
      'The Guardian of Ratio Reef rises! "Ratios, rates, proportions, conversions — master them all!"',
      [
        prob(`problem-5-${ch}-14-1`,`level-5-${ch}-14`,1,{s:'A car gets 30 miles per gallon. How many gallons are needed for a 450-mile trip?',a:num(15,'450÷30=15 gallons'),h:[hint(1,'Gallons = distance ÷ rate.','conceptual'),hint(2,'450÷30=?','directional'),hint(3,'15 gallons.','scaffolded')],sol:'15 gallons',tp:'Fuel problems: gallons = distance ÷ miles per gallon. 450 ÷ 30 = 15 gallons.',tags:['ratios','unit-rate','boss'],d:5}),
        prob(`problem-5-${ch}-14-2`,`level-5-${ch}-14`,2,{s:'Orange juice is mixed in ratio 3:7 (concentrate to water). If you have 9 cups of concentrate, how many cups of juice TOTAL will you make?',a:num(30,'9 cups = 3 parts → 1 part = 3 cups. Total = 10 parts × 3 = 30 cups'),h:[hint(1,'Total parts = 3+7 = 10.','conceptual'),hint(2,'9 cups of concentrate = 3 parts, so 1 part = 3 cups.','directional'),hint(3,'Total = 10 parts × 3 cups = 30 cups.','scaffolded')],sol:'30 cups total',tp:'Find the value per part, then multiply by total parts. 9÷3=3 cups/part × 10 parts = 30 cups.',tags:['ratios','part-whole','boss'],d:5}),
        prob(`problem-5-${ch}-14-3`,`level-5-${ch}-14`,3,{cat:'working_backwards',s:'A school has teachers and students in ratio 1:15. There are 480 people total. How many teachers?',a:num(30,'1+15=16 parts. 480÷16=30 per part. Teachers=1×30=30'),h:[hint(1,'Total ratio parts = 1+15 = 16.','conceptual'),hint(2,'480÷16=30 per part.','directional'),hint(3,'Teachers = 30.','scaffolded')],sol:'30 teachers',tp:'Ratio 1:15, total 480. Each part = 480/16 = 30. Teachers = 1 part = 30.',tags:['ratios','part-whole','boss'],d:5}),
      ]),
  ];
  return { id:cid,worldId:'world-5',number:ch,name:'Ratio Reef',topic:'ratios-rates',weekStart:22,weekEnd:24,levels,
    learningObjectives:['Write and simplify ratios','Create equivalent ratios and ratio tables','Calculate unit rates','Convert units using ratios','Solve proportional reasoning problems'],
    signatureContent:['ratio notation','equivalence','unit rates','conversions','proportions'],isBoss:true };
}

// ━━━ CHAPTER 9 — Decimal Depths ━━━━━━━━━━━━━━━━━━━━━━━━
function createChapter9() {
  const ch=9, cid=`chapter-5-${ch}`;
  const levels = [
    lev(`level-5-${ch}-1`,cid,1,'Place Value Plunge','teaching',1,
      'Prof. Owlbert dives into Decimal Depths. "Decimals extend place value past the ones place: tenths, hundredths, thousandths!"',
      [
        prob(`problem-5-${ch}-1-1`,`level-5-${ch}-1`,1,{type:'multiple_choice',inp:'multiple_choice',s:'In 3.74, what does the 7 represent? A) 7 ones B) 7 tenths C) 7 hundredths D) 7 thousandths',a:mc('B) 7 tenths','B — The first digit after the decimal point is the tenths place'),h:[hint(1,'The first place after the decimal point is tenths.','conceptual'),hint(2,'3.74: 3 is ones, 7 is tenths, 4 is hundredths.','directional'),hint(3,'7 is in the tenths place = 7/10 = 0.7.','scaffolded')],sol:'7 tenths',tp:'Decimal places: tenths (first), hundredths (second), thousandths (third). In 3.74: 7 tenths, 4 hundredths.',tags:['decimals','place-value'],d:1}),
        prob(`problem-5-${ch}-1-2`,`level-5-${ch}-1`,2,{type:'multiple_choice',inp:'multiple_choice',s:'What is 0.05 as a fraction? A) 1/5 B) 1/50 C) 1/20 D) 5/10',a:mc('C) 1/20','C — 0.05 = 5/100 = 1/20'),h:[hint(1,'0.05 = 5 hundredths.','conceptual'),hint(2,'5/100 simplifies by dividing by 5.','directional'),hint(3,'5/100 = 1/20.','scaffolded')],sol:'0.05 = 5/100 = 1/20',tp:'0.05 is in the hundredths place: 5/100 = 1/20.',tags:['decimals','place-value','fractions'],d:1}),
        prob(`problem-5-${ch}-1-3`,`level-5-${ch}-1`,3,{type:'text_input',inp:'text_field',s:'Write 0.125 as a fraction in simplest form.',a:txt('1/8','125/1000 = 1/8'),h:[hint(1,'0.125 = 125 thousandths = 125/1000.','conceptual'),hint(2,'Simplify by dividing by 125.','directional'),hint(3,'125/1000 = 1/8.','scaffolded')],sol:'0.125 = 1/8',tp:'0.125 = 125/1000 = 1/8. Knowing common decimal-fraction equivalents is very useful!',tags:['decimals','fractions','conversion'],d:1}),
      ]),
    lev(`level-5-${ch}-2`,cid,2,'Comparing Decimals','teaching',2,
      'Lizzie compares decimals. "Line up the decimal points, then compare digit by digit from left to right."',
      [
        prob(`problem-5-${ch}-2-1`,`level-5-${ch}-2`,1,{cat:'compare_without_calc',type:'text_input',inp:'text_field',s:'Which is greater: 0.35 or 0.305? Write the greater number.',a:txt('0.35','0.350 > 0.305 — tenths are the same (3), but hundredths: 5>0'),h:[hint(1,'Line up: 0.350 vs 0.305. Compare digit by digit.','conceptual'),hint(2,'Tenths: both 3. Hundredths: 5 vs 0.','directional'),hint(3,'5 > 0, so 0.35 > 0.305.','scaffolded')],sol:'0.35 > 0.305',tp:'Pad with zeros to the same length: 0.350 vs 0.305. Compare digit by digit from the left.',tags:['decimals','comparing','compare-without-calc'],d:2}),
        prob(`problem-5-${ch}-2-2`,`level-5-${ch}-2`,2,{cat:'compare_without_calc',type:'text_input',inp:'text_field',s:'Which is greater: 0.8 or 0.79? Write the greater number.',a:txt('0.8','0.80 > 0.79'),h:[hint(1,'Pad 0.8 to 0.80, then compare.','conceptual'),hint(2,'0.80 vs 0.79. Tenths: 8 vs 7.','directional'),hint(3,'8 > 7, so 0.8 > 0.79.','scaffolded')],sol:'0.8 > 0.79',tp:'0.8 = 0.80, which is clearly greater than 0.79. Adding trailing zeros does not change a decimal value.',tags:['decimals','comparing'],d:2}),
        prob(`problem-5-${ch}-2-3`,`level-5-${ch}-2`,3,{type:'text_input',inp:'text_field',s:'Order from least to greatest: 0.5, 0.05, 0.55, 0.505',a:txt('0.05, 0.5, 0.505, 0.55','Pad: 0.500, 0.050, 0.550, 0.505'),h:[hint(1,'Pad all to thousandths: 0.500, 0.050, 0.550, 0.505.','conceptual'),hint(2,'Now compare: 050 < 500 < 505 < 550.','directional'),hint(3,'0.05, 0.5, 0.505, 0.55.','scaffolded')],sol:'0.05 < 0.5 < 0.505 < 0.55',tp:'To order decimals: pad with zeros to the same number of decimal places, then compare as whole numbers.',tags:['decimals','ordering'],d:2}),
      ]),
    lev(`level-5-${ch}-3`,cid,3,'Ordering Decimals','practice',2,
      'Grogg arranges decimals in order. "I pad them with zeros and compare like whole numbers!"',
      [
        prob(`problem-5-${ch}-3-1`,`level-5-${ch}-3`,1,{type:'text_input',inp:'text_field',s:'Order from least to greatest: 2.3, 2.03, 2.33, 2.303',a:txt('2.03, 2.3, 2.303, 2.33','Pad: 2.300, 2.030, 2.330, 2.303'),h:[hint(1,'Pad to thousandths: 2.300, 2.030, 2.330, 2.303.','conceptual'),hint(2,'030 < 300 < 303 < 330.','directional'),hint(3,'2.03, 2.3, 2.303, 2.33.','scaffolded')],sol:'2.03, 2.3, 2.303, 2.33',tp:'Same technique: pad, compare, order. 2.030 < 2.300 < 2.303 < 2.330.',tags:['decimals','ordering'],d:2}),
        prob(`problem-5-${ch}-3-2`,`level-5-${ch}-3`,2,{type:'text_input',inp:'text_field',s:'Which is the smallest: 0.1, 0.01, 0.11, 0.101?',a:txt('0.01','0.010 < 0.100 < 0.101 < 0.110'),h:[hint(1,'Pad to thousandths and compare.','conceptual'),hint(2,'0.010, 0.100, 0.110, 0.101.','directional'),hint(3,'0.010 is smallest = 0.01.','scaffolded')],sol:'0.01 is smallest',tp:'Each decimal place to the right is 10× smaller: 0.1 = 10×0.01. So 0.01 is much smaller than 0.1.',tags:['decimals','ordering','place-value'],d:2}),
        prob(`problem-5-${ch}-3-3`,`level-5-${ch}-3`,3,{type:'text_input',inp:'text_field',s:'Put in order from greatest to least: 1.5, 1.05, 1.55, 1.005',a:txt('1.55, 1.5, 1.05, 1.005','Greatest first'),h:[hint(1,'Pad: 1.500, 1.050, 1.550, 1.005.','conceptual'),hint(2,'550 > 500 > 050 > 005.','directional'),hint(3,'1.55, 1.5, 1.05, 1.005.','scaffolded')],sol:'1.55, 1.5, 1.05, 1.005',tp:'Greatest to least is just the reverse. The number of decimal places does not determine size — 1.5 > 1.005.',tags:['decimals','ordering','descending'],d:2}),
      ]),
    lev(`level-5-${ch}-4`,cid,4,'Adding Decimals','teaching',2,
      'Prof. Owlbert adds decimals. "Line up the decimal points, then add like whole numbers!"',
      [
        prob(`problem-5-${ch}-4-1`,`level-5-${ch}-4`,1,{type:'text_input',inp:'text_field',s:'Add: 3.45 + 2.3',a:txt('5.75','3.45+2.30=5.75'),h:[hint(1,'Line up decimal points: 3.45 + 2.30.','conceptual'),hint(2,'5+0=5, 4+3=7, 3+2=5.','directional'),hint(3,'5.75.','scaffolded')],sol:'5.75',tp:'Pad with zeros so both have the same decimal places, then add column by column.',tags:['decimals','addition'],d:2}),
        prob(`problem-5-${ch}-4-2`,`level-5-${ch}-4`,2,{type:'text_input',inp:'text_field',s:'Add: 4.567 + 3.8',a:txt('8.367','4.567+3.800=8.367'),h:[hint(1,'Pad: 4.567+3.800.','conceptual'),hint(2,'7+0=7, 6+0=6, 5+8=13 (carry 1), 4+3+1=8.','directional'),hint(3,'8.367.','scaffolded')],sol:'8.367',tp:'When adding decimals with different numbers of places, pad with zeros first. 4.567 + 3.800 = 8.367.',tags:['decimals','addition','carrying'],d:2}),
        prob(`problem-5-${ch}-4-3`,`level-5-${ch}-4`,3,{type:'text_input',inp:'text_field',s:'Add: 12.75 + 8.5 + 0.25',a:txt('21.5','12.75+8.50+0.25=21.50=21.5'),h:[hint(1,'Line up all three: 12.75+8.50+0.25.','conceptual'),hint(2,'75+50+25=150=1.50 carry 1. 12+8+0+1=21.','directional'),hint(3,'21.50=21.5.','scaffolded')],sol:'21.5',tp:'Adding multiple decimals: line up decimal points, add column by column, carry as needed.',tags:['decimals','addition','multiple'],d:2}),
      ]),
    lev(`level-5-${ch}-5`,cid,5,'Subtracting Decimals','practice',2,
      'Lizzie subtracts decimals. "Same as addition — line up the points, then subtract!"',
      [
        prob(`problem-5-${ch}-5-1`,`level-5-${ch}-5`,1,{type:'text_input',inp:'text_field',s:'Subtract: 5.8 - 3.25',a:txt('2.55','5.80-3.25=2.55'),h:[hint(1,'Pad: 5.80-3.25.','conceptual'),hint(2,'0-5 needs borrowing: 10-5=5. 7-2=5. 5-3=2.','directional'),hint(3,'2.55.','scaffolded')],sol:'2.55',tp:'Pad with zeros before subtracting: 5.80 - 3.25 = 2.55.',tags:['decimals','subtraction'],d:2}),
        prob(`problem-5-${ch}-5-2`,`level-5-${ch}-5`,2,{type:'text_input',inp:'text_field',s:'Subtract: 10 - 3.75',a:txt('6.25','10.00-3.75=6.25'),h:[hint(1,'Write 10 as 10.00.','conceptual'),hint(2,'10.00-3.75. Borrow as needed.','directional'),hint(3,'6.25.','scaffolded')],sol:'6.25',tp:'When subtracting a decimal from a whole number, add .00 to the whole number first.',tags:['decimals','subtraction','whole-number'],d:2}),
        prob(`problem-5-${ch}-5-3`,`level-5-${ch}-5`,3,{type:'text_input',inp:'text_field',s:'Subtract: 7.4 - 2.875',a:txt('4.525','7.400-2.875=4.525'),h:[hint(1,'Pad 7.4 to 7.400.','conceptual'),hint(2,'400-875 needs borrowing from the 7.','directional'),hint(3,'7.400-2.875=4.525.','scaffolded')],sol:'4.525',tp:'Pad to the same number of decimal places, then subtract column by column with borrowing.',tags:['decimals','subtraction','borrowing'],d:2}),
      ]),
    lev(`level-5-${ch}-6`,cid,6,'Multiplying Decimals','teaching',3,
      'Grogg multiplies decimals. "Multiply as if they are whole numbers, then count decimal places!"',
      [
        prob(`problem-5-${ch}-6-1`,`level-5-${ch}-6`,1,{type:'text_input',inp:'text_field',s:'Multiply: 0.3 × 0.4',a:txt('0.12','3×4=12. Total decimal places: 1+1=2. So 0.12'),h:[hint(1,'Multiply 3×4=12. Then count total decimal places.','conceptual'),hint(2,'0.3 has 1 place. 0.4 has 1 place. Total=2.','directional'),hint(3,'12 with 2 decimal places = 0.12.','scaffolded')],sol:'0.12',tp:'Decimal multiplication: multiply the digits, then place the decimal point. Total decimal places = sum of both factors\' decimal places.',tags:['decimals','multiplication'],d:3}),
        prob(`problem-5-${ch}-6-2`,`level-5-${ch}-6`,2,{type:'text_input',inp:'text_field',s:'Multiply: 2.5 × 1.4',a:txt('3.5','25×14=350. 1+1=2 decimal places → 3.50=3.5'),h:[hint(1,'25×14=350. Count decimal places.','conceptual'),hint(2,'2.5 has 1 place, 1.4 has 1 place. Total=2.','directional'),hint(3,'350 with 2 places = 3.50 = 3.5.','scaffolded')],sol:'3.5',tp:'2.5 × 1.4: multiply 25×14=350, then place 2 decimal points → 3.50.',tags:['decimals','multiplication'],d:3}),
        prob(`problem-5-${ch}-6-3`,`level-5-${ch}-6`,3,{type:'text_input',inp:'text_field',s:'Multiply: 0.06 × 0.5',a:txt('0.03','6×5=30. 2+1=3 decimal places → 0.030=0.03'),h:[hint(1,'6×5=30. Count: 0.06 has 2 places, 0.5 has 1. Total=3.','conceptual'),hint(2,'30 with 3 places needs a leading zero: 0.030.','directional'),hint(3,'0.030=0.03.','scaffolded')],sol:'0.03',tp:'When the product has fewer digits than decimal places needed, add leading zeros: 30 → 0.030 → 0.03.',tags:['decimals','multiplication','leading-zeros'],d:3}),
      ]),
    lev(`level-5-${ch}-7`,cid,7,'Decimal Multiplication Practice','practice',3,
      'Lizzie checks results by estimating. "Does 2.5 × 1.4 ≈ 2 × 1.5 = 3? Our answer of 3.5 is close. "',
      [
        prob(`problem-5-${ch}-7-1`,`level-5-${ch}-7`,1,{type:'text_input',inp:'text_field',s:'Multiply: 3.2 × 4.5',a:txt('14.4','32×45=1440. 1+1=2 places → 14.40=14.4'),h:[hint(1,'32×45=1440. Two total decimal places.','conceptual'),hint(2,'1440 → 14.40.','directional'),hint(3,'14.4.','scaffolded')],sol:'14.4',tp:'Estimate first: 3×5=15. Our answer 14.4 is close — this confirms it is reasonable.',tags:['decimals','multiplication','estimation'],d:3}),
        prob(`problem-5-${ch}-7-2`,`level-5-${ch}-7`,2,{type:'text_input',inp:'text_field',s:'Multiply: 0.12 × 5',a:txt('0.6','12×5=60. 2 decimal places → 0.60=0.6'),h:[hint(1,'12×5=60. 0.12 has 2 places.','conceptual'),hint(2,'60 with 2 places → 0.60.','directional'),hint(3,'0.6.','scaffolded')],sol:'0.6',tp:'Multiplying a decimal by a whole number: the result has the same number of decimal places as the decimal factor.',tags:['decimals','multiplication','whole-number'],d:3}),
        prob(`problem-5-${ch}-7-3`,`level-5-${ch}-7`,3,{type:'text_input',inp:'text_field',s:'Multiply: 1.5 × 1.5',a:txt('2.25','15×15=225. 2 places → 2.25'),h:[hint(1,'15×15=225. Two total decimal places.','conceptual'),hint(2,'225 → 2.25.','directional'),hint(3,'2.25.','scaffolded')],sol:'2.25',tp:'1.5² = 2.25. Squaring a decimal: square the digits, then double the decimal places.',tags:['decimals','multiplication','squaring'],d:3}),
      ]),
    lev(`level-5-${ch}-8`,cid,8,'Dividing Decimals','teaching',3,
      'Prof. Owlbert divides. "To divide by a decimal, move the decimal point to make the divisor a whole number."',
      [
        prob(`problem-5-${ch}-8-1`,`level-5-${ch}-8`,1,{type:'text_input',inp:'text_field',s:'Divide: 4.5 ÷ 0.5',a:txt('9','Move decimal: 45÷5=9'),h:[hint(1,'Move both decimals one place right: 45÷5.','conceptual'),hint(2,'45÷5=9.','directional'),hint(3,'9.','scaffolded')],sol:'9',tp:'To divide by a decimal: move both decimal points right until the divisor is a whole number. 4.5÷0.5 = 45÷5 = 9.',tags:['decimals','division'],d:3}),
        prob(`problem-5-${ch}-8-2`,`level-5-${ch}-8`,2,{type:'text_input',inp:'text_field',s:'Divide: 7.2 ÷ 0.3',a:txt('24','72÷3=24'),h:[hint(1,'Move decimals: 72÷3.','conceptual'),hint(2,'72÷3=24.','directional'),hint(3,'24.','scaffolded')],sol:'24',tp:'7.2 ÷ 0.3 = 72 ÷ 3 = 24. Moving the decimal is equivalent to multiplying both by 10.',tags:['decimals','division'],d:3}),
        prob(`problem-5-${ch}-8-3`,`level-5-${ch}-8`,3,{type:'text_input',inp:'text_field',s:'Divide: 3.6 ÷ 0.12',a:txt('30','360÷12=30'),h:[hint(1,'Move both decimals 2 places: 360÷12.','conceptual'),hint(2,'360÷12=30.','directional'),hint(3,'30.','scaffolded')],sol:'30',tp:'3.6 ÷ 0.12 = 360 ÷ 12 = 30. Move the decimal point enough places to make the divisor a whole number.',tags:['decimals','division','two-places'],d:3}),
      ]),
    lev(`level-5-${ch}-9`,cid,9,'Decimal Division Practice','practice',3,
      'Grogg practices decimal division. "Move the point, then divide normally!"',
      [
        prob(`problem-5-${ch}-9-1`,`level-5-${ch}-9`,1,{type:'text_input',inp:'text_field',s:'Divide: 15.6 ÷ 1.2',a:txt('13','156÷12=13'),h:[hint(1,'Move both one place: 156÷12.','conceptual'),hint(2,'156÷12=13.','directional'),hint(3,'13.','scaffolded')],sol:'13',tp:'15.6÷1.2=156÷12=13.',tags:['decimals','division','practice'],d:3}),
        prob(`problem-5-${ch}-9-2`,`level-5-${ch}-9`,2,{type:'text_input',inp:'text_field',s:'Divide: 2.5 ÷ 0.25',a:txt('10','250÷25=10'),h:[hint(1,'Move 2 places: 250÷25.','conceptual'),hint(2,'250÷25=10.','directional'),hint(3,'10.','scaffolded')],sol:'10',tp:'2.5÷0.25=250÷25=10. This means 0.25 fits into 2.5 exactly 10 times.',tags:['decimals','division'],d:3}),
        prob(`problem-5-${ch}-9-3`,`level-5-${ch}-9`,3,{type:'text_input',inp:'text_field',s:'A board is 9.6 meters long. It is cut into pieces 0.8 meters each. How many pieces?',a:txt('12','96÷8=12'),h:[hint(1,'Divide: 9.6÷0.8.','conceptual'),hint(2,'Move: 96÷8=12.','directional'),hint(3,'12 pieces.','scaffolded')],sol:'12 pieces',tp:'Division word problems: 9.6÷0.8=96÷8=12 pieces.',tags:['decimals','division','word-problem'],d:3}),
      ]),
    lev(`level-5-${ch}-10`,cid,10,'Fractions to Decimals','teaching',2,
      'Prof. Owlbert connects fractions and decimals. "Every fraction IS a decimal — just divide the numerator by the denominator!"',
      [
        prob(`problem-5-${ch}-10-1`,`level-5-${ch}-10`,1,{type:'text_input',inp:'text_field',s:'Convert 3/4 to a decimal.',a:txt('0.75','3÷4=0.75'),h:[hint(1,'Divide numerator by denominator: 3÷4.','conceptual'),hint(2,'3÷4=0.75.','directional'),hint(3,'3/4=0.75.','scaffolded')],sol:'3/4=0.75',tp:'To convert a fraction to a decimal, divide: numerator ÷ denominator. 3÷4=0.75.',tags:['decimals','fractions','conversion'],d:2}),
        prob(`problem-5-${ch}-10-2`,`level-5-${ch}-10`,2,{type:'text_input',inp:'text_field',s:'Convert 1/8 to a decimal.',a:txt('0.125','1÷8=0.125'),h:[hint(1,'1÷8=?','conceptual'),hint(2,'8 goes into 1.000 → 0.125.','directional'),hint(3,'1/8=0.125.','scaffolded')],sol:'1/8=0.125',tp:'1/8 = 0.125. Common fractions to memorize: 1/2=0.5, 1/4=0.25, 1/5=0.2, 1/8=0.125.',tags:['decimals','fractions','conversion'],d:2}),
        prob(`problem-5-${ch}-10-3`,`level-5-${ch}-10`,3,{type:'text_input',inp:'text_field',s:'Convert 2/3 to a decimal (round to 2 decimal places).',a:txt('0.67','2÷3=0.666...≈0.67'),h:[hint(1,'2÷3=0.666...','conceptual'),hint(2,'This is a repeating decimal. Round to 2 places.','directional'),hint(3,'0.67 (rounded).','scaffolded')],sol:'2/3≈0.67',tp:'Some fractions give repeating decimals: 1/3=0.333..., 2/3=0.666.... Round when asked.',tags:['decimals','fractions','repeating'],d:2}),
      ]),
    lev(`level-5-${ch}-11`,cid,11,'Decimals to Fractions','practice',3,
      'Lizzie converts back. "Read the decimal, write the fraction, simplify!"',
      [
        prob(`problem-5-${ch}-11-1`,`level-5-${ch}-11`,1,{type:'text_input',inp:'text_field',s:'Convert 0.6 to a fraction in simplest form.',a:txt('3/5','6/10=3/5'),h:[hint(1,'0.6=6/10. Simplify.','conceptual'),hint(2,'GCF(6,10)=2.','directional'),hint(3,'6/10=3/5.','scaffolded')],sol:'0.6=3/5',tp:'0.6=6/10=3/5. Read the decimal (6 tenths), write as fraction, simplify.',tags:['decimals','fractions','conversion'],d:3}),
        prob(`problem-5-${ch}-11-2`,`level-5-${ch}-11`,2,{type:'text_input',inp:'text_field',s:'Convert 0.375 to a fraction in simplest form.',a:txt('3/8','375/1000=3/8'),h:[hint(1,'0.375=375/1000.','conceptual'),hint(2,'GCF(375,1000)=125.','directional'),hint(3,'375÷125/1000÷125=3/8.','scaffolded')],sol:'0.375=3/8',tp:'0.375=375/1000=3/8. Divide by GCF(375,1000)=125.',tags:['decimals','fractions','conversion'],d:3}),
        prob(`problem-5-${ch}-11-3`,`level-5-${ch}-11`,3,{type:'text_input',inp:'text_field',s:'Convert 0.45 to a fraction in simplest form.',a:txt('9/20','45/100=9/20'),h:[hint(1,'0.45=45/100.','conceptual'),hint(2,'GCF(45,100)=5.','directional'),hint(3,'45/100=9/20.','scaffolded')],sol:'0.45=9/20',tp:'0.45=45/100=9/20. Always simplify by dividing both by the GCF.',tags:['decimals','fractions','conversion'],d:3}),
      ]),
    lev(`level-5-${ch}-12`,cid,12,'Decimal Challenges','challenge',4,
      'Admiral Axiom poses decimal puzzles. "Place the decimal point in exactly the right spot!"',
      [
        prob(`problem-5-${ch}-12-1`,`level-5-${ch}-12`,1,{cat:'pattern_discovery',type:'text_input',inp:'text_field',s:'0.1 × 0.1 = ? (How many decimal places?)',a:txt('0.01','1×1=1. 1+1=2 places → 0.01'),h:[hint(1,'Multiply digits: 1×1=1. Count decimal places.','conceptual'),hint(2,'0.1 has 1 place + 0.1 has 1 place = 2 places.','directional'),hint(3,'1 with 2 decimal places = 0.01.','scaffolded')],sol:'0.01',tp:'0.1 × 0.1 = 0.01. Each multiplication by 0.1 moves the decimal one place left. Pattern: 0.1ⁿ = 10⁻ⁿ.',tags:['decimals','multiplication','pattern-discovery'],d:4}),
        prob(`problem-5-${ch}-12-2`,`level-5-${ch}-12`,2,{cat:'pattern_discovery',s:'What is 99.99 ÷ 9.9? (Move decimal, then divide.)',a:txt('10.1','999.9÷99=10.1... actually: 9999÷99=101.0... Hmm let me recalculate. 99.99/9.9=999.9/99. 99×10=990, 999.9-990=9.9, 9.9/99=0.1. So answer=10.1'),type:'text_input',inp:'text_field',h:[hint(1,'Move one decimal place: 999.9÷99.','conceptual'),hint(2,'99×10=990. 999.9-990=9.9. 9.9/99=0.1.','directional'),hint(3,'10+0.1=10.1.','scaffolded')],sol:'10.1',tp:'99.99÷9.9=10.1. Division with decimals: move the point, then use long division.',tags:['decimals','division','challenge'],d:4}),
        prob(`problem-5-${ch}-12-3`,`level-5-${ch}-12`,3,{s:'A number multiplied by 0.25 gives 5. What is the number?',a:num(20,'x×0.25=5, x=5÷0.25=20'),h:[hint(1,'0.25x=5. Divide both sides by 0.25.','conceptual'),hint(2,'5÷0.25 = 500÷25.','directional'),hint(3,'500÷25=20.','scaffolded')],sol:'x=5÷0.25=20',tp:'Dividing by 0.25 is the same as multiplying by 4. So x=5×4=20.',tags:['decimals','working-backwards','division'],d:4}),
      ]),
    lev(`level-5-${ch}-13`,cid,13,'Guardian of Decimal Depths','boss',5,
      'The Guardian of Decimal Depths demands total mastery! "All operations + conversions. Prove your worth!"',
      [
        prob(`problem-5-${ch}-13-1`,`level-5-${ch}-13`,1,{type:'text_input',inp:'text_field',s:'Calculate: 3.75 + 2.8 - 1.05',a:txt('5.5','3.75+2.80=6.55. 6.55-1.05=5.50=5.5'),h:[hint(1,'Add first, then subtract.','conceptual'),hint(2,'3.75+2.80=6.55.','directional'),hint(3,'6.55-1.05=5.50=5.5.','scaffolded')],sol:'5.5',tp:'Multi-step decimal arithmetic: work left to right. 3.75+2.80=6.55, then 6.55-1.05=5.50.',tags:['decimals','multi-step','boss'],d:5}),
        prob(`problem-5-${ch}-13-2`,`level-5-${ch}-13`,2,{type:'text_input',inp:'text_field',s:'Calculate: 2.4 × 1.5 ÷ 0.6',a:txt('6','2.4×1.5=3.6. 3.6÷0.6=36÷6=6'),h:[hint(1,'Multiply first, then divide.','conceptual'),hint(2,'2.4×1.5=3.6.','directional'),hint(3,'3.6÷0.6=6.','scaffolded')],sol:'6',tp:'2.4×1.5=3.6, then 3.6÷0.6=6. Follow order of operations left to right for ×÷.',tags:['decimals','multi-step','boss'],d:5}),
        prob(`problem-5-${ch}-13-3`,`level-5-${ch}-13`,3,{type:'text_input',inp:'text_field',s:'Convert 7/8 to a decimal.',a:txt('0.875','7÷8=0.875'),h:[hint(1,'Divide 7 by 8.','conceptual'),hint(2,'8 into 7.000: 0.875.','directional'),hint(3,'7/8=0.875.','scaffolded')],sol:'0.875',tp:'7/8=0.875. Common conversions: 1/8=0.125, 3/8=0.375, 5/8=0.625, 7/8=0.875.',tags:['decimals','fractions','boss'],d:5}),
      ]),
  ];
  return { id:cid,worldId:'world-5',number:ch,name:'Decimal Depths',topic:'decimals',weekStart:25,weekEnd:27,levels,
    learningObjectives:['Understand decimal place value to thousandths','Compare and order decimals','Add, subtract, multiply, and divide decimals','Convert between fractions and decimals'],
    signatureContent:['place value','decimal operations','decimal placement rules','fraction-decimal conversion'],isBoss:true };
}

export function createChapters7to9() {
  return [createChapter7(), createChapter8(), createChapter9()];
}
